### CRIAR USUARIO
POST http://localhost:3000/user
Content-Type: application/json

{
  "displayName": "A Freitas",
  "email": "lucas@email.com",
  "password": "123456",
  "image": "http://imagem.com/img.png"
}


### REALIZAR LOGIN
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "lucas@email.com",
  "password": "123456"
}

### GET USERS
GET http://localhost:3000/user
Content-Type: application/json
Authorization: token-123

### GET USERS BY ID
GET http://localhost:3000/user/1
Content-Type: application/json
Authorization: token-123

### POST CREATE CATEGORY
POST http://localhost:3000/categories
Content-Type: application/json
Authorization: token-123

{
  "name": "Negócios"
}